language: python
services: sqlite
env:
  - DJANGO_VERSION=1.6
python:
  - "2.7"
install:
  - "pip install -q django==$DJANGO_VERSION"
  - "python setup.py -q install"
  - "pip install -r requirements.txt"
script: "py.test tests/"
